version: "3"
services:

  nginx:
    ports:
    # NB
    # - the local port is also hardcoded in nginx/project-$DEPLOY_TYPE.conf
    # - elda will not work on any port other than 80
    # - TODO: CR login and logout actions ignore the port and redirect to port 80
    - 127.0.0.1:81:80

  plone:
    build:
      context: ./docker/plone/
    image: digitalagendadata/plone
    environment:
      SPARQL_DEBUG: "on"

  virtuoso:
    ports:
      - 127.0.0.1:8891:8890

#  elda:
#    build:
#      context: ./docker/elda

#  rsync-server:
#    image: eeacms/rsync:latest
#    container_name: rsync
#    restart: "no"
#    ports:
#      - 127.0.0.1:2222:22/tcp
#    command:
#      - server
#    environment:
#      - SSH_AUTH_KEY="ssh-rsa ..."
#      - TZ=Europe/Copenhagen
#    tty: true
#    stdin_open: true
#    volumes:
#    - virtuoso_db:/virtuoso-data
#    - maria_db:/var/lib/mysql
#    - cr_home:/var/local/cr/apphome
#    - zeodata:/plone-data
