version: "2"
services:

  memcached:
    image: memcached:1.5.7-alpine
    restart: always
    environment:
      TZ: "${TZ}"
    command:
    - -m
    - "2048"

  plone:
    image: digitalagendadata/scoreboard.plone
    restart: always
    depends_on:
    - zeoserver
    - memcached
    environment:
      ZEO_ADDRESS: "zeoserver:8080"
      MEMCACHE_SERVER: "memcached:11211"
      SOLR_URL: "http://solr:8983/solr/scoreboard"

  haproxy:
    image: eeacms/haproxy:1.7-4.0
    restart: always
    depends_on:
    - plone
    environment:
      BACKENDS: "plone"
      BACKENDS_PORT: "8080"
      DNS_ENABLED: "True"
      TZ: "${TZ}"

  zeoserver:
    image: plone/plone:4.3.17
    restart: always
    command:
      - zeo
    volumes:
      - zeodata:/data

  solr:
    image: solr:6.6.3-slim
    restart: always
    volumes: 
      - solrdata:/opt/solr/server/solr/mycores
      - ./solr:/core-template:ro
    entrypoint:
      - docker-entrypoint.sh
      - solr-precreate
      - scoreboard 
      - ${SOLR_SCOREBOARD_LOCATION}
    


  virtuoso:
     image: openlink/virtuoso_opensource:v07.20.3217
     restart: always     
     volumes:
       - ./virtuoso:/opt/virtuoso-opensource/database
       - virtuoso_db:/data
       - exported_datasets:/var/www/html/download

  content_registry:
     image: digitalagendadata/scoreboard.contreg
     restart: always
     depends_on:
     - virtuoso
     volumes:
       - content_registry:/var/local/cr/apphome
     environment:
       TZ: "${TZ}"
       HOME_URL: "${SCOREBOARD_URL}/data"
       DB_HOST: virtuoso
       DB_PORT: 1111
       DB_USER: cr3user
       DB_PASSWORD: ${CR_DB_PASSWORD}
       DB_RO_USER: cr3rouser
       DB_RO_PASSWORD: ${CR_DB_RO_PASSWORD}

  mariadb:
    image: mariadb:10.2.14
    volumes:
      - maria_db:/var/lib/mysql
    restart: always
    environment:
       TZ: "${TZ}"
       MYSQL_ROOT_PASSWORD: ${MARIADB_PASSWORD}
       MYSQL_DATABASE: piwik
       MYSQL_USER: piwik
       MYSQL_PASSWORD: ${MARIADB_PIWIK_PASSWORD}

  piwik:
    image: matomo:3.5.0-fpm
    restart: always
    links:
    - mariadb:db
    volumes:
    - piwik_files:/var/www/html/
    environment:
       TZ: "${TZ}"
       MYSQL_ROOT_PASSWORD: ${MARIADB_PASSWORD}


  nginx:
    image: nginx:1.13
    depends_on:
    - haproxy
    - piwik
    - solr
    restart: always
    ports:
    - 80:80
    volumes:
    - ./nginx/globals.conf:/etc/nginx/conf.d/globals.conf:ro
    - ./nginx/project.conf:/etc/nginx/conf.d/project.conf:ro
    - piwik_files:/var/www/html/ 
    - exported_datasets:/export/download
    environment:
    - TZ=${TZ}


  elda:
    image: digitalagendadata/scoreboard.elda
    restart: always
    links:
    - nginx:${ELDA_BASE_URL}
    environment:
    - TZ=${TZ}
    - ELDA_BASE_URL=${ELDA_BASE_URL}
 
  cron:
    image: digitalagendadata/scoreboard.cron
    restart: always
    hostname: crontab
    volumes:
    - ./cron/cron_jobs.txt:/var/crontab.txt
    - ./cron/scripts:/var/cron/scripts
    - ./cron/ssh:/root/.ssh
    - codelists:/var/local/rdf
    - exported_datasets:/var/www/html/download
    environment:
    - CRONTAB_SPARQL_ENDPOINT=http://virtuoso:8890/sparql
    - CRONTAB_ISQL_HOST=virtuoso
    - CRONTAB_ISQL_PORT=1111
    - CRONTAB_ISQL_USER=dba
    - CRONTAB_ISQL_PASSWORD=${VIRTUOSO_DBA_PASSWORD}
    - CRONTAB_CONTREG_URL=${SCOREBOARD_URL}
    - CRONTAB_SOLR_URL=http://solr:8983/solr
    - RUN_RDF_EXPORT=no

volumes:
  maria_db:
  virtuoso_db:
  content_registry:
  zeodata:
  solrdata:
  codelists:
  exported_datasets:
  piwik_files:
  plone_data:

