version: "2"
services:

  memcached:
    image: memcached:1.5.7-alpine
    environment:
      TZ: "Europe/Bucharest"
    command:
    - -m
    - "2048"

  plone:
    build: plone
    links:
    - zeoserver
    - memcached
    - solr
    environment:
      ZEO_ADDRESS: "zeo:8080"
      MEMCACHE_SERVER: "memcached:11211"
      SOLR_URL: "http://solr:8983/solr/scoreboard"

  haproxy:
    image: eeacms/haproxy:1.7-4.0
    ports:
      - "8440:5000"
    environment:
      BACKENDS: "plone"
      BACKENDS_PORT: "8080"
      DNS_ENABLED: "True"
      TZ: "Europe/Bucharest"

  zeoserver:
    image: plone/plone:4.3.17
    command:
      - zeo
    volumes:
      - zeodata:/data

  solr:
    image: solr:6.6.3-slim
    volumes: 
      - solrdata:/opt/solr/server/solr/mycores
      - ./solr:/core-template:ro
    ports:
      - 8983:8983
    entrypoint:
      - docker-entrypoint.sh
      - solr-precreate
      - scoreboard
      - ${SOLR_SCOREBOARD_LOCATION}
    


  virtuoso:
     image: openlink/virtuoso_opensource:v07.20.3217
     volumes_from:
     - plone
     volumes:
       - ./virtuoso:/opt/virtuoso-opensource/database
       - virtuoso_db:/data
     ports:
       - 8890:8890

  content_registry:
     image: contreg
     volumes:
       - content_registry:/var/local/cr/apphome
     links:
       - virtuoso
     environment:
       TZ: "${TZ}"
       HOME_URL: http://test-cr.digital-agenda-data.eu
       DB_HOST: virtuoso
       DB_PORT: 1111
       DB_USER: cr3user
       DB_PASSWORD: ${CR_DB_PASSWORD}
       DB_RO_USER: cr3rouser
       DB_RO_PASSWORD: ${CR_DB_RO_PASSWORD}

  mariadb:
    image: mariadb:10.2.14
    volumes:
      - maria_db:/var/lib/mysql
    restart: always
    environment:
       TZ: "${TZ}"
       MYSQL_ROOT_PASSWORD: ${MARIADB_PASSWORD}
       MYSQL_DATABASE: piwik
       MYSQL_USER: piwik
       MYSQL_PASSWORD: ${MARIADB_PIWIK_PASSWORD}

  piwik:
    image: matomo:3.5.0-fpm
    links:
    - mariadb:db
    environment:
       TZ: "${TZ}"
       MYSQL_ROOT_PASSWORD: ${MARIADB_PASSWORD}


  nginx:
    image: nginx:1.13
    depends_on:
    - piwik
    ports:
    - 80:80
    volumes_from:
    - piwik
    volumes:
    - ./nginx/globals.conf:/etc/nginx/conf.d/globals.conf:ro
    - ./nginx/project.conf:/etc/nginx/conf.d/project.conf:ro
    
  elda:
    image: elda
    ports:
      - 8082:8080
      - 8445:8443

  cron:
    image: cron
    hostname: crontab
    volumes_from:
     - plone
    links:
    - virtuoso
    volumes:
    - ./cron/cron_jobs.txt:/var/crontab.txt
    - ./cron/scripts/:/var/cron/scripts
    - ./cron/ssh:/root/.ssh
    - codelists:/var/local/rdf
    environment:
    - CRONTAB_SPARQL_ENDPOINT=http://virtuoso:8890/sparql
    - CRONTAB_ISQL_HOST=virtuoso
    - CRONTAB_ISQL_PORT=1111
    - CRONTAB_ISQL_USER=dba
    - CRONTAB_ISQL_PASSWORD=${VIRTUOSO_DBA_PASSWORD}
    - CRONTAB_CONTREG_URL=http://test.digital-agenda-data.eu
    - CRONTAB_SOLR_URL=http://solr:8983/solr
    - RUN_RDF_EXPORT=no

volumes:
  maria_db:
  virtuoso_db:
  content_registry:
  zeodata:
  solrdata:
  codelists:
