version: "3"
services:

  nginx:
    ports:
    # NB
    # - the local port is also hardcoded in nginx/project-$DEPLOY_TYPE.conf
    # - elda will not work on any port other than 80
    # - TODO: CR login and logout actions ignore the port and redirect to port 80
    - 127.0.0.1:81:80

  plone:
    build:
      context: ./docker/plone/staging
    image: digitalagendadata/scoreboard.plone.staging
    environment:
      SPARQL_DEBUG: "on"

  elda:
    build:
      context: ./docker/elda

  rsync-server:
    image: eeacms/rsync:latest
    restart: "no"
    ports:
      - 127.0.0.1:2222:22/tcp
    command:
      - server
    environment:
      - SSH_AUTH_KEY="ssh-rsa ..."
      - TZ=Europe/Copenhagen
    tty: true
    stdin_open: true
    volumes:
    - virtuoso_db:/data
    - maria_db:/var/lib/mysql
