version: "3"
services:

  memcached:
    image: memcached:1.5.7-alpine
    restart: always
    environment:
      TZ: "${TZ}"
    command:
    - -m
    - "2048"

  plone:
    image: digitalagendadata/plone
    restart: always
    depends_on:
    - zeoserver
    environment:
      ZEO_ADDRESS: "zeoserver:8080"
      MEMCACHE_SERVER: "memcached:11211"
      SOLR_URL: "http://solr:8983/solr/scoreboard"

  haproxy:
    image: eeacms/haproxy:1.8-1.3
    restart: always
    depends_on:
    - plone
    environment:
      BACKENDS: "plone"
      BACKENDS_PORT: "8080"
      DNS_ENABLED: "True"
      TZ: "${TZ}"

  zeoserver:
    image: plone/plone:4.3.17
    restart: always
    command:
      - zeo
    volumes:
      - zeodata:/data

  solr:
    image: solr:6.6.3-slim
    restart: always
    volumes: 
      - solrdata:/opt/solr/server/solr/mycores
      - ./solr:/core-template:ro
    entrypoint:
      - docker-entrypoint.sh
      - solr-precreate
      - scoreboard
      - /core-template/scoreboard-${DEPLOY_TYPE}
    

  virtuoso:
     image: tenforce/virtuoso:virtuoso7.2.5
     restart: always
     volumes:
       - virtuoso_db:/data
       - virtuoso_logs:/logs
       - virtuoso_backup:/backup
       - exported_datasets:/export/download
       - ./virtuoso-scripts:/virtuoso-scripts
       - ./migration_packages:/var/local/cr/apphome/migration_packages
     environment:
      VIRT_Database_ErrorLogFile: "/logs/virtuoso.log"
      VIRT_HTTPServer_ServerPort: 8890
      VIRT_HTTPServer_HTTPLogFile: "/logs/virtuoso-http.log"
      VIRT_HTTPServer_DefaultMailServer: "mail:25"
      VIRT_HTTPServer_MaxClientConnections: 4
      VIRT_HTTPServer_ServerThreads: 4
      VIRT_Parameters_ServerPort: 1111
      VIRT_Parameters_NumberOfBuffers: 170000
      VIRT_Parameters_MaxDirtyBuffers: 130000
      VIRT_Parameters_DirsAllowed: "., /backup, /export/download, /tmp, /usr/local/virtuoso-opensource/share/virtuoso/vad, /var/local/cr/apphome/migration_packages"
      VIRT_SPARQL_ResultSetMaxRows: 1000000
      VIRT_SPARQL_ResultSetMaxRows: 1000000
      VIRT_SPARQL_MaxQueryCostEstimationTime: 50000
      VIRT_SPARQL_MaxQueryExecutionTime: 300
      VIRT_SPARQL_DefaultQuery: "PREFIX qb: <http://purl.org/linked-data/cube#>
        PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
        PREFIX dad-prop: <http://semantic.digital-agenda-data.eu/def/property/>
        select distinct ?dataset where { ?obs a qb:Observation; qb:dataSet ?dataset }"
      VIRT_URIQA_DynamicLocal: 1

  cr:
     image: digitalagendadata/cr
     restart: always
     volumes:
       - cr_home:/var/local/cr/apphome
       - cr_logs:/usr/local/tomcat/logs
       - ./migration_packages:/var/local/cr/apphome/migration_packages
     environment:
       TZ: "${TZ}"
       HOME_URL: "${SCOREBOARD_URL}/data"
       DB_HOST: virtuoso
       DB_PORT: 1111
       DB_USER: cr3user
       DB_PASSWORD: ${CR_DB_PASSWORD}
       DB_RO_USER: cr3rouser
       DB_RO_PASSWORD: ${CR_DB_RO_PASSWORD}
       SPARQL_ENDPOINT: ${SPARQL_ENDPOINT}
       CR_INSTANCES: ${CR_INSTANCES}

  mariadb:
    image: mariadb:10.2.14
    volumes:
      - maria_db:/var/lib/mysql
    restart: always
    environment:
       TZ: "${TZ}"
       MYSQL_ROOT_PASSWORD: ${MARIADB_PASSWORD}
       MYSQL_DATABASE: piwik
       MYSQL_USER: piwik
       MYSQL_PASSWORD: ${MARIADB_PIWIK_PASSWORD}

  piwik:
    image: matomo:3.7-fpm
    restart: always
    links:
    - mariadb:db
    volumes:
    - piwik_files:/var/www/html
    - ./piwik/www-${DEPLOY_TYPE}.conf:/usr/local/etc/php-fpm.d/www.conf
    environment:
       TZ: "${TZ}"
       MYSQL_ROOT_PASSWORD: ${MARIADB_PASSWORD}


  nginx:
    image: digitalagendadata/nginx
    depends_on:
    - haproxy
    - piwik
    - solr
    restart: always
    volumes:
    - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    - ./nginx/globals.conf:/etc/nginx/conf.d/globals.conf:ro
    - ./nginx/project-${DEPLOY_TYPE}.conf:/etc/nginx/conf.d/project.conf:ro
    - piwik_files:/var/www/html
    - exported_datasets:/export/download
    - geoipdb:/usr/share/geoip/
    environment:
    - TZ=${TZ}


#  elda:
#    image: digitalagendadata/scoreboard.elda
#    restart: always
#    links:
#    - "nginx:${SCOREBOARDBASE_URL}"
#    environment:
#    - TZ=${TZ}
#    - SPARQL_ENDPOINT=${SPARQL_ENDPOINT}

  cron:
    image: digitalagendadata/scoreboard.cron:1.1
    restart: always
    hostname: crontab
    volumes:
    - ./cron/cron_jobs.txt:/var/crontab.txt
    - ./cron/scripts:/var/cron/scripts
    - ./cron/ssh:/root/.ssh
    - codelists:/var/local/rdf
    - exported_datasets:/export/download
    - geoipdb:/usr/share/geoip/
    environment:
    - CRONTAB_SPARQL_ENDPOINT=http://virtuoso:8890/sparql
    - CRONTAB_ISQL_HOST=virtuoso
    - CRONTAB_ISQL_PORT=1111
    - CRONTAB_ISQL_USER=dba
    - CRONTAB_ISQL_PASSWORD=${VIRTUOSO_DBA_PASSWORD}
    - CRONTAB_SCOREBOARD_URL=http://plone:8080/Plone
    - CRONTAB_SOLR_URL=http://solr:8983/solr
    - CRONTAB_DEPLOY_TYPE=${DEPLOY_TYPE}

  mail:
    image: eeacms/postfix
    restart: always
    hostname: digital-agenda-data.eu
    environment:
    - MTP_HOST=digital-agenda-data.eu
    - MTP_DESTINATION=digital-agenda-data.eu

volumes:
  maria_db:
  virtuoso_db:
  virtuoso_logs:
  virtuoso_backup:
  cr_home:
  cr_logs:
  zeodata:
  solrdata:
  codelists:
  exported_datasets:
  piwik_files:
  geoipdb:
