INSERT INTO "CR"."cr3user"."post_harvest_script" (target_source_url,target_type_url,title,script,position_number,active,run_once,last_modified) values
(NULL, 'http://reference.data.gov.uk/def/reference/URIset', 'Remove "Gregorian" from the start of skos:prefLabel', 'PREFIX skos: <http://www.w3.org/2004/02/skos/core#> MODIFY GRAPH ?harvestedSource DELETE { ?s skos:prefLabel ?oldLabel. } INSERT { ?s skos:prefLabel `xsd:string(bif:trim(fn:replace(?oldLabel,"Gregorian","")))` } WHERE { GRAPH ?harvestedSource { ?s skos:prefLabel ?oldLabel filter(strStarts(str(?oldLabel),"Gregorian")) } }', 1, 'Y', 'Y', now());

INSERT INTO "CR"."cr3user"."post_harvest_script" (target_source_url,target_type_url,title,script,position_number,active,run_once,last_modified) values
(NULL, 'http://reference.data.gov.uk/def/reference/URIset', 'Remove "Gregorian" from the start of rdfs:label', 'PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#> MODIFY GRAPH ?harvestedSource DELETE { ?s rdfs:label ?oldLabel. } INSERT { ?s rdfs:label `xsd:string(bif:trim(fn:replace(?oldLabel,"Gregorian","")))` } WHERE { GRAPH ?harvestedSource { ?s rdfs:label ?oldLabel filter(strStarts(str(?oldLabel),"Gregorian")) } }', 2, 'Y', 'Y', now());

INSERT INTO "CR"."cr3user"."post_harvest_script" (target_source_url,target_type_url,title,script,position_number,active,run_once,last_modified) values
(NULL, 'http://reference.data.gov.uk/def/reference/URIset', 'Add skos:notation and skos:altLabel', 'PREFIX skos: <http://www.w3.org/2004/02/skos/core#> INSERT INTO GRAPH ?harvestedSource { ?s skos:notation `xsd:string(bif:trim(fn:substring-after(?prefLabel,":")))`. ?s skos:altLabel `xsd:string(bif:trim(fn:substring-after(?prefLabel,":")))` } WHERE { GRAPH ?harvestedSource { ?s skos:prefLabel ?prefLabel filter(regex(?prefLabel,":")) } }', 3, 'Y', 'Y', now());

INSERT INTO "CR"."cr3user"."post_harvest_script" (target_source_url,target_type_url,title,script,position_number,active,run_once,last_modified) values
(NULL, 'http://reference.data.gov.uk/def/reference/URIset', 'Generate 3-letter months in skos:prefLabel of UK time service months', 'PREFIX skos: <http://www.w3.org/2004/02/skos/core#> DELETE { graph ?g { ?s skos:prefLabel ?oldLabel } } INSERT { graph ?g { ?s skos:prefLabel `concat(bif:left(bif:monthname(bif:stringdate(concat(?notation, "-01"))), 3), " ", bif:left(?notation, 4))` } } WHERE { GRAPH ?g { ?s a <http://reference.data.gov.uk/def/intervals/Month> . ?s skos:prefLabel ?oldLabel . ?s skos:notation ?notation } }', 4, 'Y', 'Y', now());

INSERT INTO "CR"."cr3user"."post_harvest_script" (target_source_url,target_type_url,title,script,position_number,active,run_once,last_modified) values
(NULL, 'http://reference.data.gov.uk/def/reference/URIset', 'Generate 3-letter months in rdfs:label of UK time service months', 'PREFIX skos: <http://www.w3.org/2004/02/skos/core#> PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#> DELETE { graph ?g { ?s rdfs:label ?oldLabel } } INSERT { graph ?g { ?s rdfs:label `concat(bif:left(bif:monthname(bif:stringdate(concat(?notation, "-01"))), 3), " ", bif:left(?notation, 4))` } } WHERE { GRAPH ?g { ?s a <http://reference.data.gov.uk/def/intervals/Month> . ?s rdfs:label ?oldLabel . ?s skos:notation ?notation } }', 5, 'Y', 'Y', now());